eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8000
spring:
  application:
    name: reservation-service
  datasource:
    password: P@ssw0rd
    url: jdbc:mysql://localhost:3306/hotelReservation
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate: